# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c16fd42250a80900731098bc2bb7eaef4a51169fc590c899ce3b56dcbda3a38a2dce2ec4bcab40591083d2bb2415eb2a028ccb173413d6e32b1ecbc5a2f042b

test:
  secret_key_base: d569fbf8397e3ed481021f30c301b04a5464c8c1cae487cf847466a33abc9256b66f247901d9513f8f67f7b3b24684a794b74b0c81e10bb08722d11d05f4ab59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
